apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: exporter
  namespace: otel
spec:
  mode: deployment
  # Use contrib version for more exporters (Demo purpose only)
  image: otel/opentelemetry-collector-contrib:0.90.1
  replicas: 3
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 2Gi
      cpu: 1
  nodeSelector:
    alpha.eksctl.io/nodegroup-name: ng-app
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:
        send_batch_max_size: 8192
    exporters:
      otlp/honeycomb:
        endpoint: api.honeycomb.io:443
        headers:
          x-honeycomb-team: ${HONEYCOMB_ACCESS_TOKEN}
      datadog:
        api:
          key: ${DATADOG_API_KEY}
      otlp/tempo:
        endpoint: ${GRAFANA_CLOUD_TEMPO_ENDPOINT}
        auth:
          authenticator: basicauth/traces
      prometheusremotewrite:
        endpoint: ${GRAFANA_CLOUD_PROM_ENDPOINT}
        auth:
          authenticator: basicauth/metrics
      loki:
        endpoint: ${GRAFANA_CLOUD_LOKI_ENDPOINT}
        auth:
          authenticator: basicauth/logs
      awsxray:
      awsemf:
    extensions:
      health_check:
      pprof:
      zpages:
      basicauth/traces:
        client_auth:
          username: "${GRAFANA_CLOUD_TRACES_USER_ID}"
          password: "${GRAFANA_CLOUD_API_KEY}"
      basicauth/metrics:
        client_auth:
          username: "${GRAFANA_CLOUD_METRICS_USER_ID}"
          password: "${GRAFANA_CLOUD_API_KEY}"
      basicauth/logs:
        client_auth:
          username: "${GRAFANA_CLOUD_LOGS_USER_ID}"
          password: "${GRAFANA_CLOUD_API_KEY}"
    service:
      extensions: [basicauth/traces, basicauth/metrics, basicauth/logs, health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog, otlp/tempo, otlp/honeycomb, awsxray]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog, prometheusremotewrite, awsemf]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog, loki]
  envFrom:
  - secretRef:
      name: otel-collector-keys