name: Deploy container images

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Apache Cassandra and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:cassandra"
          push: true
          tags: ghcr.io/yukim/cassandra:4.0-otel
      - name: Build Management API for Apache Cassandra and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:management-api-for-cassandra"
          push: true
          tags: ghcr.io/yukim/cass-management-api:4.0-otel