apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: otel-demo
  serverType: cassandra
  serverVersion: "4.0.5"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: server-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  resources:
    requests:
      memory: 8Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 2
  nodeAffinityLabels:
    alpha.eksctl.io/nodegroup-name: ng-cassandra
  racks:
    - name: rack1
      nodeAffinityLabels:
        topology.kubernetes.io/zone: ap-northeast-1a
    - name: rack2
      nodeAffinityLabels:
        topology.kubernetes.io/zone: ap-northeast-1c
    - name: rack3
      nodeAffinityLabels:
        topology.kubernetes.io/zone: ap-northeast-1d
  podTemplateSpec:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: otel-sidecar
    spec:
      containers:
        - name: cassandra
          image: ghcr.io/yukim/cass-management-api:4.0-otel
          imagePullPolicy: Always
          env:
          - name: OTEL_TRACES_SAMPLER
            value: parentbased_traceidratio
          - name: OTEL_TRACES_SAMPLER_ARG
            value: "0.01"
          - name: OTEL_LOGS_EXPORTER
            value: otlp
  config:
    jvm-server-options:
      initial_heap_size: "4G"
      max_heap_size: "4G"
      # Need to increase stack size (-Xss) because of okhttp3
      per_thread_stack_size: "512K"
      additional-jvm-opts:
      - -Dcassandra.enable_opentelemetry=true
    cassandra-yaml:
      num_tokens: 16
      allocate_tokens_for_local_replication_factor: 3
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager